name: release

on:
  push: { tags: ["v[0-9]+.[0-9]+.[0-9]+*"] }

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    env: { GH_TOKEN: "${{ github.token }}" }

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        with: { version: 10 }

      - run: pnpm install
      - run: pnpm review
      - run: pnpm test

      - run: pnpm changelog check ${{ github.ref_name }}
      - run: pnpm --silent changelog > .changelog
      - run: >-
          gh release create ${{ github.ref_name }} 
          --title ${{ github.ref_name }} 
          -F .changelog
